### ISSUE TITLE
Metrics not showing

### ISSUE THREAD

**Issue by kikisp** [amelbakry/kdave-chart#2] opened 2022-08-01 09:31 UTC
Hey Ahmed
Thanks for this useful chart..we deployed it successfully ..pods are running logs are showing:

```
[2022-07-29 23:17:45,572| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,509| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,530| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
```
so i guess its working?

Metrics are showing in prometheus:
```
# HELP wf_k8s_deprecated_versions_job_info Deprecated API versions Job information
# TYPE wf_k8s_deprecated_versions_job_info gauge
wf_k8s_deprecated_versions_job_info{duration_seconds="",last_run="2022-07-29T23:17:35"} 1.0
# HELP wf_k8s_deprecated_versions_info Deprecated API versions
# TYPE wf_k8s_deprecated_versions_info gauge
# HELP wf_k8s_deployed_releases Total number of the deployed releases
# TYPE wf_k8s_deployed_releases gauge
wf_k8s_deployed_releases 0.0
# HELP wf_k8s_deployed_releases_with_deprecated_api_version Total number of the deployed releases that have deprecated apiVersions
# TYPE wf_k8s_deployed_releases_with_deprecated_api_version gauge
wf_k8s_deployed_releases_with_deprecated_api_version 0.0
# HELP wf_k8s_deployed_releases_with_removed_api_version Total number of the deployed releases that have removed apiVersions
# TYPE wf_k8s_deployed_releases_with_removed_api_version gauge
wf_k8s_deployed_releases_with_removed_api_version 0.0
```
As you can see metrics are not showing any deprecations
and we for sure have some deprecated api-s..
are we doing something wrong or maybe its a bug?
Thank you

**Comment by amelbakry** [comment] 2022-08-01 09:39
Hey Stefan,

Looks like you are using helm v3? if it's the case, please provide the helm binary as helm3 in your values file https://github.com/amelbakry/kdave-chart/blob/main/values.yaml#L85-L86 otherwise it'll try to collect the deployed helmv2 releases and thus no deprecated api is found

Thanks

**Comment by kikisp** [comment] 2022-08-01 09:44
Thanks for fast answer..Yea we are using helm 3 for deploys..
here is a snippet from our deployment yaml
```
  deployment:
    automountServiceAccountToken: true
    containers:
      imageRepository: aelbakry
      imageName: kdave-server
      imageTag: 1.0.2
      args:
        - --data-file=/app/data/data.json
        - --helm-binary=helm3
      volumeMounts:
        - name: kdave-exporter-volume
          mountPath: /app/data/
    securityContext:
      runAsUser: 1003
      runAsGroup: 1003
    volumes:
      - name: kdave-exporter-volume
        persistentVolumeClaim:
          claimName: kdave-exporter-pvc-kdave-data
```
so i guess its already there

**Comment by amelbakry** [comment] 2022-08-01 09:50
Well, have you tried to use the kdave CLI to verify and check any random release to see if it uses deprecated apiVersions or not? Also, what apiVersion for which object do you think it's deprecated and it's not shown in kdave. Could you please provide an example, might be kdave deprecation policy https://github.com/wayfair-incubator/kdave/blob/main/config/versions.yaml needs to be updated

**Comment by kikisp** [comment] 2022-08-01 10:25
to be honest running kdave cli locally wasnt posible because of access issues to our clusters.
but i can share report from other tool..in this case pluto
<img width="774" alt="Screenshot 2022-08-01 at 12 24 40" src="https://user-images.githubusercontent.com/4484226/182128690-491db4e5-2c11-4398-bc71-5a16898ffc4b.png">

**Comment by amelbakry** [comment] 2022-08-01 10:45
Looks like it's a permission issue for kdave while it's running in your cluster.
from your first comment `wf_k8s_deployed_releases 0.0` kdave is not able to see any deployed release, so it makes sense that there are no deprecated apiVersions.
You can test this in a local kind cluster to narrow down the issue and if it's didn't work, I can replicate your kind cluster setup and see what's wrong

**Comment by kikisp** [comment] 2022-08-01 10:50
Yea but i am not seeing and issues in pod logs..No mentions of permissions or something like that ..
other thing that i noticed is that adding --debug to args breaks kdave..i get pod error that says no such flag.

**Comment by amelbakry** [comment] 2022-08-01 11:03
You're right, ignore that. If it's a permission issue, the pod will fail and we'll have something in the logs.
But still, the problem is that it's not able to see any deployed release in the cluster

Can you share the end of the logs of the kdave pod, also how many releases in the cluster (it may be still running and checking if the number of releases are high and the metrics will be updated at the end)

**Comment by amelbakry** [comment] 2022-08-01 11:19
If these are the end of the logs in the kdave pod
```
[2022-07-29 23:17:45,572| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,509| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,530| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
```
This means the job is still running and the metrics will be updated once the job is done

**Comment by kikisp** [comment] 2022-08-01 11:24
Nope this are a the head of the log so at the start .. now i am seeing just a lots of:
`[2022-08-01 11:14:51] "GET /metrics HTTP/1.1" 200 1083 0.002011` prometheus scraping metrics..
we dont have too much releases it is definitely finished by now..
i have a feeling thats something related to helm3.. i can try to deploy something with helm 2 and see if it will get picked up

**Comment by amelbakry** [comment] 2022-08-01 11:30
When the job is done, you should see some logs similar to these
```
[2022-08-01 02:45:41,709| INFO| helm-handler] Data file is outdated or doesn't exist. Building a new data file
[2022-08-01 02:45:41,709| INFO| helm-handler] Writing data to data file: data/data.json
```
After that, the metrics will be updated
If you see these entries in the logs `GET /metrics` doesn't mean the job is finished

**Comment by kikisp** [comment] 2022-08-01 11:38
oh i didnt saw those ..
```
args:
        - --data-file=/app/data/data.json
        - --helm-binary=helm3
      volumeMounts:
        - name: kdave-exporter-volume
          mountPath: /app/data/
    securityContext:
      runAsUser: 1003
      runAsGroup: 1003
    volumes:
      - name: kdave-exporter-volume
        persistentVolumeClaim:
          claimName: kdave-exporter-pvc-kdave-data
   ```
   maybe my volume setup is wrong and it cant write..but than i guess i would find something in logs about not able to write to fle
   i doubt that it takes so much time to finish.. i deploy it like on friday..

**Comment by amelbakry** [comment] 2022-08-01 11:52
Yup, this could be the reason. Try to ssh to the pod and see if the file exists `/app/data/data.json`
The job normally takes ~1h for ~3k releases since helm operations are already slow. But this is an estimation that is different based on the cluster setup as well

**Comment by kikisp** [comment] 2022-08-01 12:38
yea nothing there.
<img width="1152" alt="Screenshot 2022-08-01 at 14 36 37" src="https://user-images.githubusercontent.com/4484226/182149450-bd0ac42d-118d-49a8-9715-fb157582691a.png">
.

**Comment by kikisp** [comment] 2022-08-01 12:40
one thing that i just noticed upon restarting deployment
```
[2022-08-01 12:33:01,068| INFO| MainProcess] Starting kdave server.                                                                                        │
│ [2022-08-01 12:33:01,069| INFO| MainProcess] Running on http://0.0.0.0:8000/                                                                               │
│ [2022-08-01 12:33:01,094| INFO| flask-app] child process calling self.run()                                                                                │
│ [2022-08-01 12:33:01,116| INFO| helm-handler] child process calling self.run()                                                                             │
│ 10.223.152.222 - - [2022-08-01 12:33:10] "GET /metrics HTTP/1.1" 200 1064 0.006616                                                                         │
│ [2022-08-01 12:33:11,131| INFO| helm-handler] Fetching helm releases to update the current data.                                                           │
│ [2022-08-01 12:33:16,857| INFO| helm-handler] Checking the used apiVersions for release: xxxxx                                                 │
│ [2022-08-01 12:33:17,051| INFO| helm-handler] Checking the used apiVersions for release: xxxxxr                                       │
│ [2022-08-01 12:33:17,649| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxx                                                │
│ [2022-08-01 12:33:17,729| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxx
│ [2022-08-01 12:33:17,739| INFO| helm-handler] Checking the used apiVersions for release: xxxxxx                                            │
│ [2022-08-01 12:33:17,794| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxt                                                │
│ [2022-08-01 12:33:18,139| INFO| helm-handler] Checking the used apiVersions for release: xxxxxx                                          │
│ [2022-08-01 12:33:18,510| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxx                                         │
│ [2022-08-01 12:33:18,745| INFO| helm-handler] Checking the used apiVersions for release: xxxxxx                                            │
│ Exception in thread put_releases_in_queue:                                                                                                                 │
│ Traceback (most recent call last):                                                                                                                         │
│   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                              │
│     self.run()                                                                                                                                             │
│   File "/usr/local/lib/python3.8/threading.py", line 870, in run                                                                                           │
│     self._target(*self._args, **self._kwargs)                                                                                                              │
│   File "/app/exporter/helper.py", line 342, in put_all_releases_v3_in_queue                                                                                │
│     next = next + max                                                                                                                                      │
│ TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by amelbakry** [comment] 2022-08-01 13:36
Oh, I remember I fixed this bug
Could you log in to the kdave pod and let me know which version is it `cat /app/exporter/__init__.py`

**Comment by kikisp** [comment] 2022-08-01 13:38
ofcourse..
its `__version__ = "0.2.3"`

**Comment by amelbakry** [comment] 2022-08-02 08:54
I double checked and confimed that I fixed this bug before, I'll dig deeper later to see what's wrong.
In the meanwhile, did you by any chance change the max flag in your values file. Also, how many release in your cluster
Thanks

**Comment by kikisp** [comment] 2022-08-02 09:33
i didnt play with max values.. we dont have so much releases.. no more than 500 i would say..

**Comment by kikisp** [comment] 2022-08-08 10:43
Hey Ahmed
any news about this? 
is there anything that i can do to help?

**Comment by amelbakry** [comment] 2022-08-08 11:00
Hey Stefan,

I'm planning to test this weekend and see what's wrong.
Thanks for your patience.

**Comment by amelbakry** [comment] 2022-08-19 16:48
Hey Stefan,

Can you please try again with the new image version `1.0.3`, the bug should be fixed in this version https://github.com/amelbakry/kdave-chart/pull/4

**Comment by kikisp** [comment] 2022-09-02 12:23
Hey Ahmed sorry for the late reply.. i was on vacation.
Just tried new 1.0.3 image and unfortunately it shows basically same error
However now i can see the log that says:
`ERROR| helm-handler] Updating helm release information was not successful.`

<img width="975" alt="Screenshot 2022-09-02 at 14 17 45" src="https://user-images.githubusercontent.com/4484226/188141860-d7074ec3-1f32-4a2d-9cdf-b38e35ba603a.png">

**Comment by amelbakry** [comment] 2022-09-06 11:04
Hey Stefan,

I tested in a local kind cluster and the issue is that you're missing the max value in your deployment. The max has a default value in the helm chart https://github.com/amelbakry/kdave-chart/blob/main/values.yaml#L84, so I don't know how it's missing in your deployment, maybe you changed something?

So to fix it just ensure that you have these args in the deployment

```
      - args:
        - --interval=12h
        - --threads=5
        - --max=100
        - --helm-binary=helm3
```

**Comment by kikisp** [comment] 2022-09-06 12:20
hey yes thats kinda fixed the issue but i now hve same stuff from as the other user here
https://github.com/amelbakry/kdave-chart/issues/3

[2022-09-06 12:02:21,747| INFO| helm-handler] Writing data to data file: /app/data/data.json
[2022-09-06 12:02:21,750| INFO| helm-handler] process shutting down
Process helm-handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/exporter/app.py", line 877, in export_deprecated_versions_metrics
    get_deprecations_for_all_releases(
  File "/app/exporter/app.py", line 795, in get_deprecations_for_all_releases
    update_data_file(data_file, app_data=app_data)
  File "/app/exporter/app.py", line 812, in update_data_file
    file.save(json.dumps(dict(app_data)))
  File "/app/exporter/helper.py", line 65, in save
    with open(self.file_name, "w+") as fd:
PermissionError: [Errno 13] Permission denied: '/app/data/data.json'

**Comment by amelbakry** [comment] 2022-10-10 21:15
Hello Stefan,
Sorry for my delay
I added the `fsGroup` to set the correct permission on the volume https://github.com/amelbakry/kdave-chart/blob/main/values.yaml#L41. Please check now

**Comment by kikisp** [comment] 2022-10-10 21:37
Works like a charm..
thank you .. we have metrics showing now

**Closed as completed** 2022-10-10 21:45 UTC
